### ISSUE TITLE
[resolved] Responsive Issue

### ISSUE THREAD

**Issue by ggsingla** [Akatsuki-discordTeam/Whiteboard-Hackathon1#2]
If the browser window is resized, all the contents on the canvas are disappeared.

**Comment by Rex-Arnab** [comment]
ok lemme check

**Comment by Rex-Arnab** [comment]
lets save the canvas after each dragLeave and we can reload the canvas on window resize

**Comment by Rex-Arnab** [comment]
Issue Resolved :P commented the resize event listner in main.js
